# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen+github@gmail.com
author_name: Stellars Henson
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_close_all_tabs_extension
project_short_description: Small extension to add menu item under 'Tabs' to allow
    close all open tabs
python_name: jupyterlab_close_all_tabs_extension
repository: ''
test: true

